<?php
// NOS INICIA/SIGUE UNA SESIÓN CON EL OBJETO DE TIPO CAMARERO
require_once '../model/camarero.php';

// CONTROLAMOS QUE ESTE INICIALIZADO EL OBJETO CAMARERO DENTRO DE SESSION. DE LO CONTRARIO TE REDIRIGE A INDEX.PHP
// ESTO LO HACEMOS PARA QUE NO PUEDAN DIRIGIRSE DIRECTAMENTE POR URL A LA PAGINA INICIAL, A NO SER QUE SEA LOGGEADO CORRECTAMENTE
if ($_SESSION['camarero']->getRol() != 2) {
    header('Location:../view/zonaRestaurante.php?tipo_espacio=Terraza&filtro_fecha=');
}

?>